function slugify(text: string) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9а-яё\s-]/gi, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 40) || 'project';
}

function extractTitle(prompt: string) {
  const first = prompt.split(/[.!?\n]/)[0]?.trim();
  return first && first.length > 3 ? first.slice(0, 60) : 'My Application';
}

export function generateProjectFiles(
  type: string,
  prompt: string,
  projectName: string
) {
  const title = projectName || extractTitle(prompt);
  const slug = slugify(title);
  const desc = prompt || 'Generated by SharkAI';

  const sharedReadme = `# ${title}

> Generated by SharkAI Autonomous AI Platform

## Description
${desc}

## Type
${type}

## Quick Start
\`\`\`bash
npm install
npm run dev
\`\`\`

## Stack
- Frontend: Next.js / React / Tailwind CSS
- Backend: Node.js API
- Database: PostgreSQL + Prisma
- Deploy: Docker + Vercel
`;

  if (type === 'website' || type === 'saas') {
    return [
      { path: 'package.json', content: JSON.stringify({
        name: slug,
        version: '1.0.0',
        private: true,
        scripts: { dev: 'npx serve public -p 3000', start: 'npx serve public -p 3000' },
        description: desc.slice(0, 120),
      }, null, 2) },
      { path: 'public/index.html', content: buildWebsiteHtml(title, desc, type === 'saas') },
      { path: 'public/styles.css', content: buildWebsiteCss() },
      { path: 'public/app.js', content: buildWebsiteJs(title) },
      { path: 'README.md', content: sharedReadme },
      { path: 'Dockerfile', content: `FROM nginx:alpine\nCOPY public /usr/share/nginx/html\nEXPOSE 80\n` },
    ];
  }

  if (type === 'api') {
    return [
      { path: 'package.json', content: JSON.stringify({
        name: slug, version: '1.0.0', type: 'module',
        scripts: { start: 'node src/server.js', dev: 'node --watch src/server.js' },
        dependencies: { express: '^4.21.0', cors: '^2.8.5' },
      }, null, 2) },
      { path: 'src/server.js', content: buildApiServer(title, desc) },
      { path: 'README.md', content: sharedReadme },
    ];
  }

  if (type === 'database') {
    return [
      { path: 'schema.prisma', content: buildPrismaSchema(slug, desc) },
      { path: 'seed.sql', content: buildSeedSql(title) },
      { path: 'README.md', content: sharedReadme },
    ];
  }

  if (type === 'mobile') {
    return [
      { path: 'pubspec.yaml', content: `name: ${slug.replace(/-/g, '_')}\ndescription: ${desc.slice(0, 80)}\nversion: 1.0.0\nenvironment:\n  sdk: '>=3.0.0 <4.0.0'\ndependencies:\n  flutter:\n    sdk: flutter\n` },
      { path: 'lib/main.dart', content: buildFlutterMain(title, desc) },
      { path: 'README.md', content: sharedReadme },
    ];
  }

  if (type === 'desktop') {
    return [
      { path: 'package.json', content: JSON.stringify({
        name: slug, version: '1.0.0', main: 'main.js',
        scripts: { start: 'electron .' },
        devDependencies: { electron: '^33.0.0' },
      }, null, 2) },
      { path: 'main.js', content: buildElectronMain(title) },
      { path: 'index.html', content: buildWebsiteHtml(title, desc, false) },
      { path: 'README.md', content: sharedReadme },
    ];
  }

  if (type === 'game') {
    return [
      { path: 'index.html', content: buildGameHtml(title, desc) },
      { path: 'game.js', content: buildGameJs() },
      { path: 'README.md', content: sharedReadme },
    ];
  }

  return [
    { path: 'package.json', content: JSON.stringify({ name: slug, version: '1.0.0' }, null, 2) },
    { path: 'src/index.ts', content: `// SharkAI Generated\n// ${desc}\n\nexport function main() {\n  console.log("${title}");\n}\n\nmain();\n` },
    { path: 'README.md', content: sharedReadme },
  ];
}

function buildWebsiteCss() {
  return `*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--cyan:#00D2FF;--blue:#0072FF;--purple:#9D50BB;--bg:#0a0e1a}
body{font-family:system-ui,sans-serif;background:var(--bg);color:#fff;line-height:1.6}
.hero{min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:2rem;background:radial-gradient(ellipse at 50% 0%,rgba(0,114,255,.15),transparent 70%)}
.hero h1{font-size:clamp(2rem,5vw,3.5rem;background:linear-gradient(90deg,var(--cyan),var(--blue),var(--purple));-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:1rem}
.hero p{color:rgba(255,255,255,.6);max-width:600px;margin-bottom:2rem}
.btn{display:inline-block;padding:.875rem 2rem;border-radius:12px;background:linear-gradient(135deg,var(--cyan),var(--purple));color:#fff;text-decoration:none;font-weight:600;transition:transform .2s}
.btn:hover{transform:scale(1.05)}
.features{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:1.5rem;padding:4rem 2rem;max-width:1100px;margin:0 auto}
.card{background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:1.5rem;backdrop-filter:blur(12px)}
.card h3{color:var(--cyan);margin-bottom:.5rem}
footer{text-align:center;padding:2rem;color:rgba(255,255,255,.4);font-size:.875rem}
`;
}

function buildWebsiteJs(title: string) {
  return `document.addEventListener('DOMContentLoaded',()=>{console.log('${title.replace(/'/g, "\\'")} loaded');const b=document.querySelector('.btn');if(b)b.addEventListener('click',e=>{e.preventDefault();alert('Welcome to ${title.replace(/'/g, "\\'")}!')})});`;
}

function buildWebsiteHtml(title: string, desc: string, isSaas: boolean) {
  const features = isSaas
    ? ['Dashboard Analytics', 'User Management', 'Subscription Billing', 'API Integration']
    : ['Modern Design', 'Mobile Responsive', 'Fast Performance', 'SEO Optimized'];

  const featureCards = features
    .map((f) => `<div class="card"><h3>${f}</h3><p>Built automatically by SharkAI multi-agent system.</p></div>`)
    .join('\n        ');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <section class="hero">
    <h1>${title}</h1>
    <p>${desc.slice(0, 200)}</p>
    <a href="#" class="btn">${isSaas ? 'Start Free Trial' : 'Get Started'}</a>
  </section>
  <section class="features">
    ${featureCards}
  </section>
  <footer>Generated by SharkAI · ${new Date().getFullYear()}</footer>
  <script src="app.js"></script>
</body>
</html>`;
}

function buildApiServer(title: string, desc: string) {
  return `import express from 'express';
import cors from 'cors';

const app = express();
app.use(cors());
app.use(express.json());

const items = [
  { id: 1, name: 'Sample Item', description: '${desc.slice(0, 80).replace(/'/g, "\\'")}' },
];

app.get('/api/health', (_, res) => res.json({ status: 'ok', service: '${title.replace(/'/g, "\\'")}' }));
app.get('/api/items', (_, res) => res.json(items));
app.post('/api/items', (req, res) => {
  const item = { id: items.length + 1, ...req.body };
  items.push(item);
  res.status(201).json(item);
});

const PORT = process.env.PORT || 4000;
app.listen(PORT, () => console.log('${title} API running on port ' + PORT));
`;
}

function buildPrismaSchema(slug: string, desc: string) {
  return `generator client { provider = "prisma-client-js" }
datasource db { provider = "postgresql" url = env("DATABASE_URL") }

// ${desc.slice(0, 100)}
model User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
  posts     Post[]
}

model Post {
  id        String   @id @default(cuid())
  title     String
  content   String?
  authorId  String
  author    User     @relation(fields: [authorId], references: [id])
  createdAt DateTime @default(now())
}
`;
}

function buildSeedSql(title: string) {
  return `-- Seed data for ${title}
INSERT INTO "User" (id, email, name) VALUES ('seed-1', 'admin@example.com', 'Admin');
`;
}

function buildFlutterMain(title: string, desc: string) {
  return `import 'package:flutter/material.dart';

void main() => runApp(const SharkApp());

class SharkApp extends StatelessWidget {
  const SharkApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${title.replace(/'/g, "\\'")}',
      theme: ThemeData.dark().copyWith(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF0072FF)),
      ),
      home: Scaffold(
        appBar: AppBar(title: Text('${title.replace(/'/g, "\\'")}')),
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Text('${desc.slice(0, 120).replace(/'/g, "\\'")}', textAlign: TextAlign.center),
          ),
        ),
      ),
    );
  }
}
`;
}

function buildElectronMain(title: string) {
  return `const { app, BrowserWindow } = require('electron');
const path = require('path');

function createWindow() {
  const win = new BrowserWindow({ width: 1200, height: 800, title: '${title.replace(/'/g, "\\'")}' });
  win.loadFile('index.html');
}
app.whenReady().then(createWindow);
`;
}

function buildGameHtml(title: string, desc: string) {
  return `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>${title} Game</title>
<style>body{margin:0;background:#0a0e1a;display:flex;flex-direction:column;align-items:center;justify-content:center;height:100vh;color:#fff;font-family:system-ui}
canvas{border:2px solid #0072FF;border-radius:8px}h1{background:linear-gradient(90deg,#00D2FF,#9D50BB);-webkit-background-clip:text;-webkit-text-fill-color:transparent}</style>
</head><body>
<h1>${title}</h1><p style="color:#888;margin:8px">${desc.slice(0, 80)}</p>
<canvas id="game" width="480" height="320"></canvas>
<script src="game.js"></script></body></html>`;
}

function buildGameJs() {
  return `const c=document.getElementById('game'),x=c.getContext('2d');
let px=240,py=160,dx=3,dy=2;
function loop(){x.fillStyle='#0a0e1a';x.fillRect(0,0,480,320);x.fillStyle='#00D2FF';x.beginPath();x.arc(px,py,12,0,Math.PI*2);x.fill();
px+=dx;py+=dy;if(px<12||px>468)dx=-dx;if(py<12||py>308)dy=-dy;requestAnimationFrame(loop)}loop();`;
}
