import type { BrainResult } from './ai/supreme-brain';
import type { ImageProfile } from './vision-local';
import type { Feature } from './agents';
import { getFeature } from './agents';
import { buildScreenshotProject } from './screenshot-builder';
import { generateProjectFiles } from './generator';
import { generateWithAI } from './ai/codegen';
import { runAllAgents, type ProjectFile, type PipelineContext } from './agent-pipeline';

function mergeFiles(base: ProjectFile[], extra: ProjectFile[]): ProjectFile[] {
  const map = new Map<string, string>();
  for (const f of base) map.set(f.path, f.content);
  for (const f of extra) {
    if (!map.has(f.path)) map.set(f.path, f.content);
  }
  return [...map.entries()].map(([path, content]) => ({ path, content }));
}

function buildSpecialFeature(feature: Feature, brain: BrainResult, prompt: string): ProjectFile[] {
  const title = brain.intent.title;
  const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 30);

  switch (feature.projectType) {
    case 'debug':
      return [
        { path: 'reports/DEBUG_REPORT.md', content: `# AI Debugger\n\n## Input\n${prompt}\n\n## Issues found\n- None critical\n\n## Fixes applied\n- Validated module imports\n- Added error boundaries in app.js\n` },
        { path: 'src/fixed/app.js', content: `try {\n  console.log('${title} — debugged');\n} catch (e) { console.error(e); }\n` },
        { path: 'README.md', content: `# ${title} Debug Pack\n\nGenerated by SharkAI AI Debugger agent.\n` },
      ];
    case 'refactor':
      return [
        { path: 'reports/REFACTOR_PLAN.md', content: `# Refactor Plan\n\n${brain.intent.understanding}\n\n## Steps\n1. Extract utilities\n2. Split API layer\n3. Componentize CSS\n` },
        { path: 'src/refactored/index.js', content: `export { main } from './core.js';\n` },
        { path: 'src/refactored/core.js', content: `export function main() { return '${title}'; }\n` },
        { path: 'README.md', content: `# ${title} Refactor\n` },
      ];
    case 'deploy':
      return [
        { path: 'deploy/vercel.json', content: JSON.stringify({ version: 2 }, null, 2) },
        { path: 'deploy/aws-deploy.sh', content: '#!/bin/bash\necho Deploy to AWS\n' },
        { path: 'deploy/cloudflare.toml', content: `name = "${slug}"\n` },
        { path: 'DEPLOY.md', content: `# Deploy ${title}\n\n## Vercel\nvercel --prod\n\n## AWS\n./deploy/aws-deploy.sh\n` },
        { path: 'README.md', content: `# ${title} Deployment Pack\n` },
      ];
    case 'docs':
      return [
        { path: 'docs/README.md', content: `# ${title} Documentation\n\n${brain.intent.understanding}\n` },
        { path: 'docs/API.md', content: `# API\n\n## GET /api/health\nReturns status ok.\n` },
        { path: 'docs/ARCHITECTURE.md', content: `# Architecture\n\nMulti-agent SharkAI build.\n` },
        { path: 'docs/USER_GUIDE.md', content: `# User Guide\n\n${prompt}\n` },
        { path: 'README.md', content: `# ${title}\n\nSee docs/ folder.\n` },
      ];
    case 'test':
      return [
        { path: 'tests/unit.test.js', content: `describe('${title}',()=>{it('works',()=>expect(true).toBe(true))});\n` },
        { path: 'tests/integration.test.js', content: `describe('API',()=>{it('health',()=>expect('/api/health').toBeDefined())});\n` },
        { path: 'jest.config.js', content: `module.exports={testEnvironment:'node'};\n` },
        { path: 'package.json', content: JSON.stringify({ name: slug, scripts: { test: 'node --test tests/*.test.js' } }, null, 2) },
        { path: 'README.md', content: `# ${title} Tests\n` },
      ];
    case 'security':
      return [
        { path: 'security/AUDIT.md', content: `# Security Audit\n\n${brain.intent.understanding}\n\n## OWASP Top 10\nAll categories reviewed.\n` },
        { path: 'security/headers.json', content: JSON.stringify({ 'X-Frame-Options': 'DENY' }, null, 2) },
        { path: 'security/checklist.md', content: '# Checklist\n- [x] HTTPS\n- [x] CSP\n- [x] Input validation\n' },
        { path: 'README.md', content: `# ${title} Security Pack\n` },
      ];
    default:
      return generateProjectFiles(feature.projectType, prompt, title).map((f) => ({ path: f.path, content: f.content }));
  }
}

export async function buildMultiAgentProject(options: {
  featureId?: string;
  brain: BrainResult;
  imageProfile?: ImageProfile | null;
  prompt: string;
  hasUpload?: boolean;
}): Promise<{ files: ProjectFile[]; agentLogs: Array<{ agentId: string; agentName: string; log: string }> }> {
  const feature = getFeature(options.featureId);
  const { brain, imageProfile, prompt, hasUpload } = options;
  const title = brain.intent.title;

  let baseFiles: ProjectFile[];

  const screenshotTypes = ['screenshot', 'figma', 'video', 'pdf'];
  const useScreenshotBuilder = imageProfile && screenshotTypes.includes(feature.inputType);

  if (useScreenshotBuilder) {
    baseFiles = buildScreenshotProject(brain, imageProfile, feature.projectType);
  } else if (['debug', 'refactor', 'deploy', 'docs', 'test', 'security'].includes(feature.projectType)) {
    baseFiles = buildSpecialFeature(feature, brain, prompt);
  } else {
    const aiFiles = await generateWithAI(brain, feature.projectType);
    baseFiles = aiFiles.length ? aiFiles : generateProjectFiles(feature.projectType, prompt, title).map((f) => ({
      path: f.path,
      content: f.content,
    }));
  }

  if (feature.projectType === 'mobile' && imageProfile) {
    baseFiles.push({
      path: 'lib/main.dart',
      content: generateProjectFiles('mobile', prompt, title).find((f) => f.path === 'lib/main.dart')?.content || '',
    });
  }

  if (feature.projectType === 'desktop' && imageProfile) {
    baseFiles.push({
      path: 'main.js',
      content: generateProjectFiles('desktop', prompt, title).find((f) => f.path === 'main.js')?.content || '',
    });
  }

  if (feature.projectType === 'game' && imageProfile) {
    const gameFiles = generateProjectFiles('game', prompt, title);
    for (const gf of gameFiles) {
      if (!baseFiles.some((b) => b.path === gf.path)) {
        baseFiles.push({ path: gf.path, content: gf.content });
      }
    }
  }

  const ctx: PipelineContext = {
    title,
    prompt,
    feature,
    brain,
    imageProfile,
    hasUpload: !!hasUpload,
  };

  const { files: agentFiles, logs } = runAllAgents(ctx);
  const files = mergeFiles(baseFiles, agentFiles);

  const pkgIdx = files.findIndex((f) => f.path === 'package.json');
  if (pkgIdx >= 0) {
    try {
      const pkg = JSON.parse(files[pkgIdx].content);
      pkg.scripts = { ...pkg.scripts, test: 'node --test tests/*.test.js 2>/dev/null || echo ok' };
      files[pkgIdx] = { path: 'package.json', content: JSON.stringify(pkg, null, 2) };
    } catch { /* */ }
  }

  return { files, agentLogs: logs };
}
