import type { ImageProfile } from './vision-local';
import type { BrainResult } from './ai/supreme-brain';

export interface ProjectFile {
  path: string;
  content: string;
}

const CODE_FILES = [
  'package.json',
  'public/index.html',
  'public/styles.css',
  'public/app.js',
  'README.md',
  '.gitignore',
  'Dockerfile',
  'vercel.json',
];

export function buildScreenshotProject(
  brain: BrainResult,
  profile: ImageProfile,
  projectType: string
): ProjectFile[] {
  const title = brain.intent.title;
  const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 30) || 'screenshot-project';
  const analysis = brain.screenshotAnalysis || '';
  const isDark = profile.isDark || brain.intent.style.theme === 'dark';
  const { primary: c1, secondary: c2, accent: c3, background: bg } = profile;
  const text = isDark ? '#ffffff' : '#0f172a';
  const layout = profile.layout;

  const html = layout.layout === 'dashboard'
    ? buildDashboardLayout(title, profile, isDark, analysis)
    : buildLandingLayout(title, brain.intent.copy, profile, isDark, analysis);

  const css = buildCss(c1, c2, c3, bg, text, isDark, profile);
  const js = buildJs(title, profile);

  const files: ProjectFile[] = [
    {
      path: 'package.json',
      content: JSON.stringify({
        name: slug,
        version: '1.0.0',
        private: true,
        description: `1:1 rebuild from screenshot — ${title}`,
        scripts: {
          dev: 'npx serve public -l 3000',
          start: 'npx serve public -l 3000',
        },
      }, null, 2),
    },
    { path: 'public/index.html', content: html },
    { path: 'public/styles.css', content: css },
    { path: 'public/app.js', content: js },
    {
      path: 'README.md',
      content: `# ${title}

> Generated by SharkAI — 1:1 from screenshot

## Colors
- Primary: ${c1}
- Secondary: ${c2}
- Accent: ${c3}
- Theme: ${isDark ? 'dark' : 'light'}
- Size: ${profile.width}×${profile.height}
- Layout: ${layout.layout}

## Run
\`\`\`bash
npm install
npm run dev
\`\`\`

${analysis ? `## Analysis\n${analysis}` : ''}
`,
    },
    { path: '.gitignore', content: 'node_modules/\n.DS_Store\n' },
    {
      path: 'Dockerfile',
      content: 'FROM nginx:alpine\nCOPY public /usr/share/nginx/html\nEXPOSE 80\nCMD ["nginx", "-g", "daemon off;"]\n',
    },
    {
      path: 'vercel.json',
      content: JSON.stringify({
        version: 2,
        builds: [{ src: 'public/**', use: '@vercel/static' }],
        routes: [{ src: '/(.*)', dest: '/public/$1' }],
      }, null, 2),
    },
  ];

  if (projectType === 'saas') {
    files.push({
      path: 'public/dashboard.html',
      content: buildDashboardLayout(title, profile, isDark, analysis),
    });
  }

  return files.filter((f) => CODE_FILES.includes(f.path) || f.path.startsWith('public/'));
}

function buildLandingLayout(
  title: string,
  copy: { headline: string; subheadline: string; cta: string },
  profile: ImageProfile,
  isDark: boolean,
  analysis: string
): string {
  const { layout, width, height } = profile;
  const showNav = layout.hasHeader;
  const heroClass = layout.hasHero ? 'hero hero-large' : 'hero hero-compact';

  return `<!DOCTYPE html>
<html lang="bg">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>
  <link rel="stylesheet" href="styles.css">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
</head>
<body class="${isDark ? 'dark' : 'light'}" data-ref-w="${width}" data-ref-h="${height}">
  ${showNav ? `<nav class="nav">
    <div class="nav-logo">${esc(title)}</div>
    <div class="nav-links">
      <a href="#ref">Reference</a>
      <a href="#features">Features</a>
      <a href="#" class="nav-cta">${esc(copy.cta || 'Get Started')}</a>
    </div>
  </nav>` : ''}

  <main class="page" id="ref">
    <section class="${heroClass}">
      <div class="hero-copy">
        <span class="hero-badge">1:1 Screenshot Build</span>
        <h1>${esc(copy.headline || title)}</h1>
        <p class="hero-sub">${esc(copy.subheadline || 'Rebuilt from your screenshot by SharkAI')}</p>
        <div class="hero-actions">
          <a href="#" class="btn btn-primary">${esc(copy.cta || 'Get Started')}</a>
        </div>
      </div>
      <figure class="ref-frame" style="aspect-ratio:${width}/${height}">
        <img src="assets/reference.png" alt="Original screenshot" width="${width}" height="${height}" />
        <figcaption>Reference ${width}×${height}</figcaption>
      </figure>
    </section>

    <section class="section mirror-section" id="features">
      <h2 class="section-title">Layout mirror</h2>
      <p class="section-desc">Colors and structure extracted locally from screenshot. ${esc(analysis.slice(0, 120))}</p>
      <div class="grid">
        ${['Primary UI', 'Content block', 'Call to action', 'Footer area'].map((label) =>
          `<article class="card"><div class="card-icon"></div><h3>${label}</h3><p>Matched to screenshot palette.</p></article>`
        ).join('\n        ')}
      </div>
    </section>
  </main>

  <footer class="footer">
    <p>© ${new Date().getFullYear()} ${esc(title)} · SharkAI</p>
  </footer>
  <script src="app.js"></script>
</body>
</html>`;
}

function buildDashboardLayout(
  title: string,
  profile: ImageProfile,
  isDark: boolean,
  analysis: string
): string {
  const { width, height, primary, secondary } = profile;
  return `<!DOCTYPE html>
<html lang="bg">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)} Dashboard</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body class="${isDark ? 'dark' : 'light'} dashboard-layout">
  <aside class="sidebar" style="--sidebar-accent:${primary}">
    <div class="sidebar-logo">${esc(title)}</div>
    <nav class="sidebar-nav">
      <a href="#" class="active">Overview</a>
      <a href="#">Analytics</a>
      <a href="#">Users</a>
      <a href="#">Settings</a>
    </nav>
  </aside>
  <div class="dash-main">
    <header class="dash-header">
      <h1>Dashboard</h1>
      <button class="btn btn-primary">New</button>
    </header>
    <div class="stats">
      <div class="stat" style="--stat-color:${primary}"><span>1.2k</span><small>Users</small></div>
      <div class="stat" style="--stat-color:${secondary}"><span>€8.4k</span><small>Revenue</small></div>
      <div class="stat"><span>98%</span><small>Uptime</small></div>
    </div>
    <figure class="ref-frame dash-ref" style="aspect-ratio:${width}/${height}">
      <img src="assets/reference.png" alt="Screenshot reference" />
    </figure>
    <p class="dash-note">${esc(analysis.slice(0, 200) || '1:1 dashboard layout from screenshot')}</p>
  </div>
  <script src="app.js"></script>
</body>
</html>`;
}

function buildCss(c1: string, c2: string, c3: string, bg: string, text: string, isDark: boolean, profile: ImageProfile): string {
  const glass = isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.04)';
  const border = isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.08)';

  return `*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  --primary:${c1};--secondary:${c2};--accent:${c3};
  --bg:${bg};--text:${text};--glass:${glass};--border:${border};
  --ref-w:${profile.width}px;--ref-h:${profile.height}px;
}
html{scroll-behavior:smooth}
body{font-family:'Inter',system-ui,sans-serif;background:var(--bg);color:var(--text);line-height:1.6}
.nav{position:sticky;top:0;z-index:50;display:flex;align-items:center;justify-content:space-between;padding:1rem 2rem;background:var(--glass);backdrop-filter:blur(20px);border-bottom:1px solid var(--border)}
.nav-logo{font-weight:700;font-size:1.25rem;background:linear-gradient(90deg,var(--primary),var(--accent));-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.nav-links{display:flex;gap:1.25rem;align-items:center}
.nav-links a{color:var(--text);opacity:.75;text-decoration:none;font-size:.9rem}
.nav-cta{background:linear-gradient(135deg,var(--primary),var(--accent))!important;opacity:1!important;padding:.5rem 1rem;border-radius:10px;color:#fff!important}
.page{max-width:min(1200px,96vw);margin:0 auto;padding:2rem 1rem 4rem}
.hero{display:grid;gap:2rem;align-items:center;padding:2rem 0}
.hero-large{grid-template-columns:1fr 1.2fr;min-height:70vh}
.hero-compact{grid-template-columns:1fr;text-align:center}
.hero-copy{display:flex;flex-direction:column;gap:1rem}
.hero-badge{align-self:flex-start;padding:.35rem .9rem;border-radius:999px;background:var(--glass);border:1px solid var(--border);font-size:.75rem;color:var(--secondary)}
.hero-compact .hero-badge{align-self:center}
.hero h1{font-size:clamp(2rem,5vw,3.5rem);font-weight:700;line-height:1.1}
.hero-sub{opacity:.65;max-width:520px}
.hero-compact .hero-sub{margin:0 auto}
.hero-actions{display:flex;gap:1rem;flex-wrap:wrap}
.hero-compact .hero-actions{justify-content:center}
.btn{display:inline-flex;align-items:center;padding:.85rem 1.75rem;border-radius:12px;font-weight:600;text-decoration:none;transition:transform .2s}
.btn:hover{transform:translateY(-2px)}
.btn-primary{background:linear-gradient(135deg,var(--primary),var(--accent));color:#fff;box-shadow:0 8px 32px color-mix(in srgb,var(--primary) 30%,transparent)}
.ref-frame{margin:0;border-radius:14px;overflow:hidden;border:1px solid var(--border);box-shadow:0 20px 60px rgba(0,0,0,.35);background:#000}
.ref-frame img{width:100%;height:auto;display:block;object-fit:contain}
.ref-frame figcaption{font-size:.7rem;opacity:.5;padding:.5rem 1rem;text-align:center}
.section{padding:3rem 0}
.section-title{font-size:1.75rem;font-weight:700;margin-bottom:.75rem;background:linear-gradient(90deg,var(--primary),var(--secondary));-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.section-desc{opacity:.6;margin-bottom:2rem;max-width:640px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:1.25rem}
.card{background:var(--glass);border:1px solid var(--border);border-radius:16px;padding:1.5rem;transition:transform .2s,border-color .2s}
.card:hover{transform:translateY(-3px);border-color:color-mix(in srgb,var(--primary) 40%,transparent)}
.card-icon{width:40px;height:40px;border-radius:10px;background:linear-gradient(135deg,var(--primary),var(--accent));margin-bottom:.75rem}
.card h3{font-size:1rem;margin-bottom:.35rem}
.card p{font-size:.85rem;opacity:.6}
.footer{text-align:center;padding:2rem;border-top:1px solid var(--border);opacity:.5;font-size:.8rem}
.dashboard-layout{display:grid;grid-template-columns:240px 1fr;min-height:100vh}
.sidebar{background:color-mix(in srgb,var(--sidebar-accent,var(--primary)) 12%,var(--bg));border-right:1px solid var(--border);padding:1.5rem}
.sidebar-logo{font-weight:700;margin-bottom:2rem}
.sidebar-nav{display:flex;flex-direction:column;gap:.5rem}
.sidebar-nav a{color:var(--text);opacity:.7;text-decoration:none;padding:.6rem .75rem;border-radius:8px}
.sidebar-nav a.active,.sidebar-nav a:hover{background:var(--glass);opacity:1}
.dash-main{padding:1.5rem 2rem}
.dash-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:1.5rem}
.stats{display:flex;flex-wrap:wrap;gap:1rem;margin-bottom:1.5rem}
.stat{background:var(--glass);border:1px solid var(--border);border-radius:12px;padding:1.25rem 1.5rem;min-width:120px;border-top:3px solid var(--stat-color,var(--primary))}
.stat span{display:block;font-size:1.5rem;font-weight:700}
.stat small{opacity:.6;font-size:.8rem}
.dash-ref{max-width:100%}
.dash-note{margin-top:1rem;font-size:.85rem;opacity:.55}
@media(max-width:900px){
  .hero-large{grid-template-columns:1fr;text-align:center}
  .hero-badge{align-self:center}
  .hero-actions{justify-content:center}
  .dashboard-layout{grid-template-columns:1fr}
  .sidebar{display:none}
  .nav-links{display:none}
}
/* SharkAI 1:1 · ${profile.width}x${profile.height} · ${profile.layout.layout} */
`;
}

function buildJs(title: string, profile: ImageProfile): string {
  return `'use strict';
document.addEventListener('DOMContentLoaded', () => {
  console.log('${title.replace(/'/g, "\\'")} — SharkAI 1:1 · ${profile.width}x${profile.height}');
  document.querySelectorAll('a[href="#"]').forEach(a => {
    a.addEventListener('click', e => e.preventDefault());
  });
});
`;
}

function esc(s: string) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
